### ISSUE TITLE
Path to deployment to staging

### ISSUE THREAD

**Issue by bdach** [ppy/osu-server-beatmap-submission#2]
This is a list of things I see as required to be done before trying to put this thing on staging. Mostly adding for myself, but also for external accountability / tracking.

```[tasklist]
### Tasks
- [ ] https://github.com/ppy/osu-server-beatmap-submission/pull/1
- [ ] https://github.com/ppy/osu-web/pull/11668
- [ ] Any required schema adjustments from aforementioned pull
- [ ] Accept pending / WIP user choice
- [ ] Address in-code TODOs regarding various safety, consistency, and logic checks
- [ ] Ensure a forum thread is created for the submitted beatmap so that its description can be edited
- [ ] S3-based beatmap storage implementation
- [ ] Use beatmap versioning tables for listing package contents rather than extracting the package
- [ ] Observability (sentry, ddog)
```
